name: Pack and Upload
description: 'Pack and Upload'
inputs:
  go_version:
    description: 'Go version to use'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup
      uses: ./.github/actions/setup
      with:
        go_version: ${{ inputs.go_version }}
        token: ${{ secrets.CI_READ_COMMON }}
