name: Setup repo
description: "Setup repo"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      env:
        # to handle cache overwrite errors
        TAR_OPTIONS: --skip-old-files
      with:
        go-version-file: go.mod
