name: Setup repo
description: "Setup repo"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      env:
        # to handle cache overwrite errors
        TAR_OPTIONS: --skip-old-files
      with:
        go-version-file: go.mod
