name: Setup repo
description: "Setup repo"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      env:
        # to handle cache overwrite errors
        TAR_OPTIONS: --skip-old-files
      with:
        go-version-file: go.mod
