name: Setup repo
description: "Setup repo"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      env:
        # to handle cache overwrite errors
        TAR_OPTIONS: --skip-old-files
      with:
        go-version-file: go.mod
