name: Setup repo
description: "Setup repo"
inputs:
  token:
    description: 'Token for the common repo'
    required: true
  go_version:
    description: "Go version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3.0.0
      with:
        go-version: ${{ inputs.go_version }}

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Configure git for private modules
      env:
        TOKEN: ${{ inputs.token }}
      run: git config --global url."https://${TOKEN}@github.com/descope".insteadOf "https://github.com/descope"
      shell: bash

    - name: Go mod vendor
      run: go mod vendor
      shell: bash
