name: Setup repo
description: "Setup repo"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      env:
        # to handle cache overwrite errors
        TAR_OPTIONS: --skip-old-files
      with:
        go-version-file: go.mod
