version: v0.18.6
formatter: default

rules:
  - header-max-length
  - body-leading-blank
  - body-max-line-length
  - footer-leading-blank
  - footer-max-line-length
  - type-enum
  - type-case
  - type-empty
  - scope-case
  - subject-empty
  - subject-full-stop

severity:
  default: error

settings:
  header-max-length:
    argument: 72
  body-max-line-length:
    argument: 100
  footer-max-line-length:
    argument: 100
  type-enum:
    argument:
      - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
  type-case:
    argument: lower
  scope-case:
    argument: lower
  subject-full-stop:
    argument: "."
    flags:
      negate: true
