name: Lint and more checks
description: "Lint and more checks"
runs:
  using: "composite"
  steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Lint and more checks
      run: |
        chmod +x ./scripts/build/ci/build_lint.sh
        ./scripts/build/ci/build_lint.sh
      shell: bash
