run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 3m

# all available settings of specific linters
linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: false
  depguard:
    rules:
      packages-with-error-message:
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  revive:
    rules:
      - name: defer
        arguments: [["loop", "return"]]
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: increment-decrement
      - name: var-naming
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: if-return
      - name: superfluous-else
      - name: unreachable-code
      - name: unused-parameter
      - name: unconditional-recursion
      - name: waitgroup-by-value
      - name: duplicated-imports
      - name: unreachable-code
      - name: context-keys-type # Might cause slowness in lint
      - name: time-naming # Might cause slowness in lint
      - name: var-declaration # Might cause slowness in lint
      - name: errorf # Might cause slowness in lint

linters:
  enable:
    - revive
    - govet
    - gofmt
    - goimports
    - godox
    - depguard
    - forbidigo
  disable-all: true

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  # exclude-rules:

  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0