package auth

import (
	"net/http"
)

// Implementation in descope/auth/auth.go
type MagicLink interface {
	// SignIn - Use to login a user based on a magic link that will be sent either email or a phone
	// and choose the selected delivery method for verification (see auth/DeliveryMethod).
	// returns an error upon failure.
	SignIn(method DeliveryMethod, identifier, URI string, r *http.Request, loginOptions *LoginOptions) error

	// SignUp - Use to create a new user based on the given identifier either email or a phone.
	// choose the selected delivery method for verification (see auth/DeliveryMethod).
	// optional to add user metadata for farther user details such as name and more.
	// returns an error upon failure.
	SignUp(method DeliveryMethod, identifier, URI string, user *User) error

	// SignUpOrIn - Use to login in using identifier, if user does not exists, a new user will be created
	// with the given identifier.
	// choose the selected delivery method for verification (see auth/DeliveryMethod).
	// optional to add user metadata for farther user details such as name and more.
	// returns an error upon failure.
	SignUpOrIn(method DeliveryMethod, identifier string, URI string) error

	// SignInCrossDevice - Use to login a user based on a magic link that will be sent either email or a phone
	// and choose the selected delivery method for verification (see auth/DeliveryMethod).
	// it will return a pending reference to be used in GetMagicLinkSession, which should get the session once the link was verified.
	// returns an error upon failure.
	SignInCrossDevice(method DeliveryMethod, identifier, URI string, r *http.Request, loginOptions *LoginOptions) (*MagicLinkResponse, error)

	// SignUpCrossDevice - Use to create a new user based on the given identifier either email or a phone.
	// choose the selected delivery method for verification (see auth/DeliveryMethod).
	// optional to add user metadata for farther user details such as name and more.
	// it will return a pending reference to be used in GetMagicLinkSession, which should get the session once the link was verified.
	// returns an error upon failure.
	SignUpCrossDevice(method DeliveryMethod, identifier, URI string, user *User) (*MagicLinkResponse, error)

	// SignUpOrInCrossDevice - Use to login in using identifier, if user does not exists, a new user will be created
	// with the given identifier.
	// choose the selected delivery method for verification (see auth/DeliveryMethod).
	// optional to add user metadata for farther user details such as name and more.
	// it will return a pending reference to be used in GetMagicLinkSession, which should get the session once the link was verified.
	// returns an error upon failure.
	SignUpOrInCrossDevice(method DeliveryMethod, identifier string, URI string) (*MagicLinkResponse, error)

	// GetSession - Use to get a session that was generated by SignIn/SignUp request, and verified with Verify request.
	GetSession(pendingRef string, w http.ResponseWriter) (*AuthenticationInfo, error)

	// Verify - Use to verify a SignIn/SignUp request, based on the magic link token generated.
	// if the link was generated with crossDevice, the authentication info will be nil, and should returned with GetSession.
	Verify(token string, w http.ResponseWriter) (*AuthenticationInfo, error)

	// UpdateUserEmail - Use to update email and validate via magiclink
	// ExternalID of user whom we want to update
	// Request is needed to obtain JWT and send it to Descope, for verification
	UpdateUserEmail(identifier, email, URI string, request *http.Request) error

	// UpdateUserEmailCrossDevice - Use to update email and validate via magiclink, with cross device options
	// ExternalID of user whom we want to update
	// Request is needed to obtain JWT and send it to Descope, for verification
	UpdateUserEmailCrossDevice(identifier, email, URI string, request *http.Request) (*MagicLinkResponse, error)

	// UpdateUserPhone - Use to update phone and validate via magiclink
	// allowed methods are phone based methods - whatsapp and SMS
	// ExternalID of user whom we want to update
	// Request is needed to obtain JWT and send it to Descope, for verification
	UpdateUserPhone(method DeliveryMethod, identifier, phone, URI string, request *http.Request) error

	// UpdateUserPhoneCrossDevice - Use to update email and validate via magiclink, with cross device options
	// allowed methods are phone based methods - whatsapp and SMS
	// ExternalID of user whom we want to update
	// Request is needed to obtain JWT and send it to Descope, for verification
	UpdateUserPhoneCrossDevice(method DeliveryMethod, identifier, phone, URI string, request *http.Request) (*MagicLinkResponse, error)
}

type OTP interface {
	// SignIn - Use to login a user based on the given identifier either email or a phone
	// and choose the selected delivery method for verification. (see auth/DeliveryMethod)
	// returns an error upon failure.
	SignIn(method DeliveryMethod, identifier string, r *http.Request, loginOptions *LoginOptions) error

	// SignUp - Use to create a new user based on the given identifier either email or a phone.
	// choose the selected delivery method for verification. (see auth/DeliveryMethod)
	// optional to add user metadata for farther user details such as name and more.
	// returns an error upon failure.
	SignUp(method DeliveryMethod, identifier string, user *User) error

	// SignUpOrIn - Use to login in using identifier, if user does not exists, a new user will be created
	// with the given identifier.
	SignUpOrIn(method DeliveryMethod, identifier string) error

	// VerifyCode - Use to verify a SignIn/SignUp based on the given identifier either an email or a phone
	// followed by the code used to verify and authenticate the user.
	// In case the request cookie can be renewed an automatic renewal is called and returns a new set of cookies to use.
	// Use the ResponseWriter (optional) to apply the cookies to the response automatically.
	// returns a list of cookies or an error upon failure.
	VerifyCode(method DeliveryMethod, identifier string, code string, w http.ResponseWriter) (*AuthenticationInfo, error)

	// UpdateUserEmail - Use to a update email, and verify via OTP
	// ExternalID of user whom we want to update
	// Request is needed to obtain JWT and send it to Descope, for verification
	UpdateUserEmail(identifier, email string, request *http.Request) error

	// UpdateUserPhone - Use to update phone and validate via OTP
	// allowed methods are phone based methods - whatsapp and SMS
	// ExternalID of user whom we want to update
	// Request is needed to obtain JWT and send it to Descope, for verification
	UpdateUserPhone(method DeliveryMethod, identifier, phone string, request *http.Request) error
}

type TOTP interface {
	// SignUp - create a new user, and create a seed for it,
	// PAY ATTENTION that this is a different flow than OTP
	// The return value will allow to connect it to an authenticator app
	SignUp(identifier string, user *User) (*TOTPResponse, error)

	// SignInCode - Use to verify a SignIn/SignUp based on the given identifier
	// followed by the code used to verify and authenticate the user.
	// In case the request cookie can be renewed an automatic renewal is called and returns a new set of cookies to use.
	// Use the ResponseWriter (optional) to apply the cookies to the response automatically.
	// returns a list of cookies or an error upon failure.
	SignInCode(identifier string, code string, r *http.Request, loginOptions *LoginOptions, w http.ResponseWriter) (*AuthenticationInfo, error)

	// UpdateUser - set a seed to an existing user, so the user can use an authenticator app
	UpdateUser(identifier string, request *http.Request) (*TOTPResponse, error)
}

type OAuth interface {
	// Start - Use to start an OAuth authentication using the given OAuthProvider.
	// returns an error upon failure and a string represent the redirect URL upon success.
	// Uses the response writer to automatically redirect the client to the provider url for authentication.
	// A successful authentication will result in a callback to the url defined in the current project settings.
	Start(provider OAuthProvider, returnURL string, r *http.Request, loginOptions *LoginOptions, w http.ResponseWriter) (string, error)

	// ExchangeToken - Finalize OAuth
	// code should be extracted from the redirect URL of OAth/SAML authentication flow
	ExchangeToken(code string, w http.ResponseWriter) (*AuthenticationInfo, error)
}

type SAML interface {
	// Start will initiate a SAML login flow
	// return will be the redirect URL that needs to return to client
	// and finalize with the ExchangeToken call
	Start(tenant string, returnURL string, r *http.Request, loginOptions *LoginOptions, w http.ResponseWriter) (redirectURL string, err error)

	// ExchangeToken - Finalize SAML authentication
	// code should be extracted from the redirect URL of OAth/SAML authentication flow
	ExchangeToken(code string, w http.ResponseWriter) (*AuthenticationInfo, error)
}

type WebAuthn interface {
	// SignUpStart - Use to start an authentication process with webauthn for the new user argument.
	// Origin is the origin of the URL for the web page where the webauthn operation is taking place, as returned
	// by calling document.location.origin via javascript.
	// returns a transaction id response on success and error upon failure.
	SignUpStart(identifier string, user *User, origin string) (*WebAuthnTransactionResponse, error)

	// SignUpFinish - Use to finish an authentication process with a given transaction id and credentials after been signed
	// by the credentials navigator.
	// Use the ResponseWriter (optional) to apply the cookies to the response automatically.
	SignUpFinish(finishRequest *WebAuthnFinishRequest, w http.ResponseWriter) (*AuthenticationInfo, error)

	// SignInStart - Use to start an authentication validation with webauthn for an existing user with the given identifier.
	// Origin is the origin of the URL for the web page where the webauthn operation is taking place, as returned
	// by calling document.location.origin via javascript.
	// returns a transaction id response on successs and error upon failure.
	SignInStart(identifier string, origin string, r *http.Request, loginOptions *LoginOptions) (*WebAuthnTransactionResponse, error)

	// SignInFinish - Use to finish an authentication process with a given transaction id and credentials after been signed
	// by the credentials navigator.
	// Use the ResponseWriter (optional) to apply the cookies to the response automatically.
	SignInFinish(finishRequest *WebAuthnFinishRequest, w http.ResponseWriter) (*AuthenticationInfo, error)

	// SignUpOrInStart - Use to start an authentication validation with webauthn, if user does not exist, a new user will be created
	// with the given identifier. The Create field in the response object determines which browser API should be called,
	// either navigator.credentials.create or navigator.credentials.get as well as whether to call SignUpFinish (if
	// Create is true) or SignInFinish (if Create is false) later to finalize the operation.
	// Origin is the origin of the URL for the web page where the webauthn operation is taking place, as returned
	// by calling document.location.origin via javascript.
	// returns a transaction id response on successs and error upon failure.
	SignUpOrInStart(identifier string, origin string) (*WebAuthnTransactionResponse, error)

	// UpdateUserDeviceStart - Use to start an add webauthn device process for an existing user with the given identifier.
	// Request is needed to obtain JWT and send it to Descope, for verification.
	// Origin is the origin of the URL for the web page where the webauthn operation is taking place, as returned
	// by calling document.location.origin via javascript.
	// returns a transaction id response on success and error upon failure.
	UpdateUserDeviceStart(identifier string, origin string, request *http.Request) (*WebAuthnTransactionResponse, error)

	// UpdateUserDeviceFinish - Use to finish an add webauthn device process with a given transaction id and credentials after been signed
	// by the credentials navigator.
	UpdateUserDeviceFinish(finishRequest *WebAuthnFinishRequest) error
}

type Authentication interface {
	MagicLink() MagicLink
	OTP() OTP
	TOTP() TOTP
	OAuth() OAuth
	SAML() SAML
	WebAuthn() WebAuthn

	// ValidateSession - Use to validate a session of a given request.
	// Should be called before any private API call that requires authorization.
	// In case the request cookie can be renewed an automatic renewal is called and returns a new set of cookies to use.
	// Use the ResponseWriter (optional) to apply the cookies to the response automatically.
	// returns true upon success or false and an error upon failure.
	ValidateSession(request *http.Request, w http.ResponseWriter) (bool, *Token, error)

	// ValidateSessionTokens - Use to validate a session of a given token.
	// Should be called before any private API call that requires authorization.
	// returns true upon success or false and an error upon failure.
	ValidateSessionTokens(sessionToken, refreshToken string) (bool, *Token, error)

	// RefreshSession - Use to force refresh of a JWT token, even though it is not expired.
	// Use the ResponseWriter (optional) to apply the cookies to the response automatically.
	// returns true upon success or false and an error upon failure.
	RefreshSession(request *http.Request, w http.ResponseWriter) (bool, *Token, error)

	// ExchangeAccessKey - Use to exchange an access key for a session token.
	ExchangeAccessKey(accessKey string) (bool, *Token, error)

	// ValidatePermissions - Use to ensure that a validated session token has been granted
	// the specified permissions.
	// This is a shortcut for ValidateTenantPermissions(token, "", permissions)
	ValidatePermissions(token *Token, permissions []string) bool
	// ValidateTenantPermissions - Use to ensure that a validated session token has been
	// granted the specified permissions for a specific tenant.
	ValidateTenantPermissions(token *Token, tenant string, permissions []string) bool

	// ValidateRoles - Use to ensure that a validated session token has been granted the
	// specified roles.
	// This is a shortcut for ValidateTenantRoles(token, "", roles)
	ValidateRoles(token *Token, roles []string) bool

	// ValidateTenantRoles - Use to ensure that a validated session token has been granted
	// the specified roles for a specific tenant.
	ValidateTenantRoles(token *Token, tenant string, roles []string) bool

	// Logout - Logs out from the current session and deletes the session and refresh cookies in the http response.
	// Use the ResponseWriter (optional) to apply the cookies to the response automatically.
	Logout(request *http.Request, w http.ResponseWriter) error

	// LogoutAll - Use to perform logout from all active sessions for the request user. This will revoke the given tokens
	// and if given options will also remove existing session on the given response sent to the client.
	// Use the ResponseWriter (optional) to apply the cookies to the response automatically.
	LogoutAll(request *http.Request, w http.ResponseWriter) error

	// Me - Use to retrieve current session user details. The request requires a valid refresh token.
	// returns the user details or error if the refresh token is not valid.
	Me(request *http.Request) (*UserResponse, error)
}
